version: '3.8'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  kafka:
    image: bitnami/kafka:3.4.0
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      ALLOW_PLAINTEXT_LISTENER: yes
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
  zookeeper:
    image: zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
  nacos:
    image: nacos/nacos-server:latest
    environment:
      MODE: standalone
      NACOS_AUTH_ENABLE: false

      NACOS_AUTH_TOKEN: dGVzdGluZ3Rva2VuZm9ybmFjb3NhdXRoMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
      NACOS_AUTH_IDENTITY_KEY: token
      NACOS_AUTH_IDENTITY_VALUE: dGVzdGluZ3Rva2VuZm9ybmFjb3NhdXRoMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
      NACOS_AUTH_SECRET_KEY: dGVzdGluZ3Rva2VuZm9ybmFjb3NhdXRoMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
    ports:
      - "8848:8848"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - gateway-service
  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - redis
      - nacos
  product-service:
    build:
      context: ./product-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql
      - redis
      - nacos
  order-service:
    build:
      context: ./order-service
    ports:
      - "8083:8083"
    depends_on:
      - mysql
      - kafka
      - nacos
  payment-service:
    build:
      context: ./payment-service
    ports:
      - "8084:8084"
    depends_on:
      - kafka
      - nacos
  gateway-service:
    build:
      context: ./gateway-service
    ports:
      - "8080:8080"
    depends_on:
      - nacos
volumes:
  mysql-data: