server:
  port: 8083

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://mysql:3306/ecommerce?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: redis
    port: 6379
  kafka:
    bootstrap-servers: kafka:9092

  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        username: nacos
        password: nacos
        # 如需 token 认证，添加如下配置
        access-key: nacos:nacos
        secret-key: nacos:nacos